<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find robot_grasp)/models/table/table_properties.xacro" />
	<gazebo reference="table_base">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="table_top">
		<material>Gazebo/White</material>
	</gazebo>
	
	<link name="table_base">
		<inertial>
			<origin xyz="0.018511509179121 0.23251932391586 1.175991980646075" rpy="0 0 0" />
			<mass value="1265032.07764878" />
			<inertia ixx="169157.982834144" ixy="-162908.934773947E-14" ixz="-974479.440236252E-15" iyy="323322.704330012" iyz="-184123.364573924E-14" izz="259218.197995528" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="$(find robot_grasp)/models/table/meshes/table_base.STL" />
			</geometry>
			<material name="">
				<color rgba="0.192156862745098 0.203921568627451 0.203921568627451 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="$(find robot_grasp)/models/table/meshes/table_base.STL" />
			</geometry>
		</collision>
	</link>
	
	<link name="table_top">
		<inertial>
			<origin xyz="2.18575157973078E-16 0.0165 -1.11022302462516E-16" rpy="0 0 0" />
			<mass value="2772000" />
			<inertia ixx="148091.559" ixy="-470197.740328915E-35" ixz="133744.867033177E-16" iyy="402517.5" iyz="0" izz="254929.059" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="$(find robot_grasp)/models/table/meshes/table_top.STL" />
			</geometry>
			<material name="">
				<color rgba="1 1 1 1" />
			</material>
		</visual>
		<visual>
			<origin xyz="0 ${t_thickness+rim_height/2} ${-t_height/2+rim_thickness/2}" rpy="0 0 0" />
			<geometry>
				<box size="${t_width} ${rim_height} ${rim_thickness}"/>
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 1 1" />
			</material>
		</visual>
		<visual>
			<origin xyz="${t_width/2-rim_thickness/2} ${t_thickness+rim_height/2} 0" rpy="0 0 0" />
			<geometry>
				<box size="${rim_thickness} ${rim_height} ${t_height}"/>
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 1 1" />
			</material>
		</visual>

		<collision>
			<origin xyz="0 ${t_thickness+rim_height/2} ${-t_height/2+rim_thickness/2}" rpy="0 0 0" />
			<geometry>
				<box size="${t_width} ${rim_height} ${rim_thickness}"/>
			</geometry>
		</collision>
		<collision>
			<origin xyz="${t_width/2-rim_thickness/2} ${t_thickness+rim_height/2} 0" rpy="0 0 0" />
			<geometry>
				<box size="${rim_thickness} ${rim_height} ${t_height}"/>
			</geometry>
		</collision> 
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="$(find robot_grasp)/models/table/meshes/table_top.STL" />
			</geometry>
		</collision>
	</link>
<!-- Added   -->
       <link name="world" />
	<joint name="j0" type="fixed">
		<origin xyz="0 0 0.273" rpy="0 0 0" />
		<parent link="world" />
		<child link="table_base" />
		<axis xyz="0 0 0" />
	</joint>  
	<joint name="j1" type="fixed">
		<origin xyz="0.0185115091791201 -0.175991980646074 0.397575968372377" rpy="1.5707963267949 0 0" />
		<parent link="table_base" />
		<child link="table_top" />
		<axis xyz="0 0 0" />
	</joint>


	<!-- Add some handy co-ordinate frames -->

	<link name="tabletop_ontop"/>
	<joint name="table_tabletop_totop" type="fixed">
		<origin xyz="0.0 0.033 0" rpy="-1.57079632679 0 0" />
		<parent link="table_top" />
		<child link="tabletop_ontop" />
		<axis xyz="0 0 0" />
	</joint>

	<link name="tabletop_corner"/>
	<joint name="set_tabletop_relto_corner" type="fixed">
		<origin xyz="0.42 0.3 0" rpy="0 0 -0.76" />
		<parent link="tabletop_ontop"/>
		<child link="tabletop_corner"/>
	</joint>

        <!-- Grasp Objects -->
	<gazebo reference="basket">
		<material>Gazebo/Green</material>
	</gazebo>
	<gazebo reference="basket2">
		<material>Gazebo/Blue</material>
	</gazebo>
	<gazebo reference="kinect_support">
		<material>Gazebo/Black</material>
	</gazebo>

	<link name="basket">
		<inertial>
			<origin xyz="0 0 0" rpy="0.2 0.3 0.4" />
			<mass value="0.1" />
			<inertia ixx="0.02" ixy="0.02" ixz="0.02" iyy="0.02" iyz="0.02" izz="0.02" />
		</inertial>
		<visual>
			<origin xyz="0 0 -0.1" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/grasp_object/basket.dae" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 -0.1" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/grasp_object/basket.dae" />
			</geometry>
		</collision>
	</link>

	<link name="basket2">
		<inertial>
			<origin xyz="0 0 0" rpy="0.2 0.3 0.4" />
			<mass value="0.1" />
			<inertia ixx="0.02" ixy="0.02" ixz="0.02" iyy="0.02" iyz="0.02" izz="0.02" />
		</inertial>
		<visual>
			<origin xyz="0 0 -0.1" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/grasp_object/basket.dae" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 -0.1" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/grasp_object/basket.dae" />
			</geometry>
		</collision>
	</link>

	<link name="kinect_support">
		<inertial>
			<origin xyz="0 0 0" rpy="0.2 0.3 0.4" />
			<mass value="0.1" />
			<inertia ixx="0.02" ixy="0.02" ixz="0.02" iyy="0.02" iyz="0.02" izz="0.02" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/table/meshes/kinect_support.dae" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.001 0.001 0.001" filename="$(find robot_grasp)/models/grasp_object/meshes/kinect_support.dae" />
			</geometry>
		</collision>
	</link>


	<joint name="table_basket" type="fixed">
		<origin xyz="0.25 0.06 0.15" rpy="0 0 0" />  <!-- relative to world coordinator: y z x -->
		<parent link="table_top" />
		<child link="basket" />
		<axis xyz="0 0 0" />
	</joint>

	<joint name="table_basket2" type="fixed">
		<origin xyz="-0.2 0.06 0.15" rpy="0 0 0" />  
		<parent link="table_top" />
		<child link="basket2" />
		<axis xyz="0 0 0" />
	</joint>

	<joint name="table_kinect_support" type="fixed">
		<origin xyz="0.1 0.19 0.3" rpy="0 -1.5707963267949 0" />  <!-- relative to world coordinator: x z -y -->
		<parent link="table_top" /> 
		<child link="kinect_support" />
		<axis xyz="0 0 0" />
	</joint>


 <!--       <gazebo reference="cubic">
	        <material>Gazebo/Yellow</material>
	</gazebo>
        <gazebo reference="cylinder">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="fourPrism">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="fourPrismoid">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="fourPyramid">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="halfSphere">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="shortCylinder">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="sixPrism">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="threePrism">
		<material>Gazebo/WoodTile</material>
	</gazebo>
        <gazebo reference="threePyramid">
		<material>Gazebo/WoodTile</material>
	</gazebo> 

      <link name="cubic">
		<inertial>
			<origin xyz="0 0 0" rpy="0.2 0.3 0.4" />
			<mass value="0.07" />
			<inertia ixx="0.02" ixy="0.02" ixz="0.02" iyy="0.02" iyz="0.02" izz="0.02" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.01 0.01 0.01" filename="$(find robot_grasp)/models/grasp_object/meshes/cubic.STL" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh scale="0.01 0.01 0.01" filename="$(find robot_grasp)/models/grasp_object/meshes/cubic.STL" />
			</geometry>
		</collision>
     </link> 

	<joint name="basket_cubic" type="floating">
		<origin xyz="0.04 0 0.03" rpy="0 0 0" />
		<parent link="basket" />
		<child link="cubic" />
		<axis xyz="0 0 0" />
	</joint>  -->


</root>
